"""Fine-tune bge-small-en-v1.5 on consultas_centro_control.json.

Two-round iterative training with chunk re-selection:
  Round 1 (warmup): Base encoder selects best chunks per query → trains
    for warmup_epochs. The encoder learns MASA semantics.
  Token expansion: Adds accented module names (Condor, Colibri, Vicuna,
    Tucan) to the tokenizer vocabulary.
  Round 2 (final): Round-1 encoder re-selects chunks with improved
    representations → trains for final_epochs (default 15). Best model
    auto-saved when evaluator score peaks — overfitting past the peak
    doesn't affect the saved checkpoint.

Uses GISTEmbedLoss (arXiv:2402.16829) to filter false negatives via a
guide model — critical because 92% of MASA doc pairs exceed 0.75 cosine
similarity, making standard MNRL in-batch negatives noisy.

Stratified split per document (15 queries each):
  - Train:  10 per doc =  540 total
  - Val:     2 per doc =  108 total (overfitting detection)
  - Test:    3 per doc =  162 total (final held-out evaluation)

Requires chunks.json generated by generate_chunks.py.

Usage:
    python -m winner_solution.scripts.finetune_encoder --device cuda
    python -m winner_solution.scripts.finetune_encoder --device cuda --warmup-epochs 5 --final-epochs 10
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from loguru import logger
from sentence_transformers import SentenceTransformer, InputExample, losses
from sentence_transformers.evaluation import InformationRetrievalEvaluator
from torch.utils.data import DataLoader

PROJECT_ROOT = Path(__file__).parent.parent
CONSULTAS_PATH = PROJECT_ROOT / "data" / "consultas_centro_control.json"
CHUNKS_PATH = PROJECT_ROOT / "artifacts" / "winner" / "chunks.json"
OUTPUT_DIR = PROJECT_ROOT / "artifacts" / "winner" / "encoder"

ENCODER_MODEL = "BAAI/bge-small-en-v1.5"

MASA_TOKENS = [
    "Cóndor", "cóndor",
    "Colibrí", "colibrí",
    "Vicuña", "vicuña",
    "Tucán", "tucán",
]

TRAIN_PER_DOC = 10
VAL_PER_DOC = 2
TEST_PER_DOC = 3


def split_consultas(consultas: list[dict]) -> tuple[list[dict], list[dict], list[dict]]:
    """Split consultas into train/val/test using stratified sampling per document.

    Each document contributes exactly TRAIN_PER_DOC + VAL_PER_DOC + TEST_PER_DOC
    queries. Queries are assigned in order: first TEST_PER_DOC to test,
    next VAL_PER_DOC to val, remaining to train.

    Args:
        consultas: Full list of consulta dicts with doc_id field.

    Returns:
        Tuple of (train, val, test) consulta lists.
    """
    by_doc: dict[str, list[dict]] = defaultdict(list)
    for c in consultas:
        by_doc[c["doc_id"]].append(c)

    train, val, test = [], [], []
    for _, doc_consultas in sorted(by_doc.items()):
        test.extend(doc_consultas[:TEST_PER_DOC])
        val.extend(doc_consultas[TEST_PER_DOC:TEST_PER_DOC + VAL_PER_DOC])
        train.extend(doc_consultas[TEST_PER_DOC + VAL_PER_DOC:])

    return train, val, test


def build_training_examples(
    consultas: list[dict],
    chunks: list[dict],
    model: SentenceTransformer,
) -> list[InputExample]:
    """Build training examples from consultas and document chunks.

    For each (query, doc_id) pair, finds the best matching chunk from the
    assigned document using cosine similarity with the base encoder. If a
    hard_negative_doc_id is present, includes the hardest chunk from that
    doc as a hard negative by the same criterion.

    Args:
        consultas: List of consulta dicts with query, doc_id, hard_negative_doc_id.
        chunks: List of all chunk dicts with doc_id and embedding_text.
        model: Base encoder used to compute cosine similarity for chunk selection.

    Returns:
        List of InputExample objects for sentence-transformers training.
    """
    chunks_by_doc: dict[str, list[dict]] = defaultdict(list)
    for chunk in chunks:
        chunks_by_doc[chunk["doc_id"]].append(chunk)

    all_chunk_texts = [c["embedding_text"] for c in chunks]
    chunk_to_idx: dict[int, int] = {id(c): i for i, c in enumerate(chunks)}

    logger.info("Embedding all chunks for cosine-based chunk selection...")
    chunk_embeddings = model.encode(
        all_chunk_texts, batch_size=64, normalize_embeddings=True, show_progress_bar=True,
    )

    query_texts = [c["query"] for c in consultas]
    logger.info("Embedding all queries for cosine-based chunk selection...")
    query_embeddings = model.encode(
        query_texts, batch_size=64, normalize_embeddings=True, show_progress_bar=True,
    )

    def best_chunk_text(q_emb: np.ndarray, doc_chunks: list[dict]) -> str:
        """Return embedding_text of the chunk with highest cosine similarity to query."""
        indices = [chunk_to_idx[id(c)] for c in doc_chunks]
        sims = chunk_embeddings[indices] @ q_emb
        return doc_chunks[int(np.argmax(sims))]["embedding_text"]

    examples = []
    for i, consulta in enumerate(consultas):
        pos_doc_id = consulta["doc_id"]
        neg_doc_id = consulta.get("hard_negative_doc_id")

        pos_chunks = chunks_by_doc.get(pos_doc_id, [])
        if not pos_chunks:
            continue

        q_emb = query_embeddings[i]
        pos_text = best_chunk_text(q_emb, pos_chunks)

        if neg_doc_id:
            neg_chunks = chunks_by_doc.get(neg_doc_id, [])
            if neg_chunks:
                neg_text = best_chunk_text(q_emb, neg_chunks)
                examples.append(InputExample(texts=[consulta["query"], pos_text, neg_text]))
                continue

        examples.append(InputExample(texts=[consulta["query"], pos_text]))

    return examples


def build_evaluator(
    consultas: list[dict],
    chunks: list[dict],
) -> InformationRetrievalEvaluator:
    """Build an IR evaluator over all validation consultas.

    Uses all provided consultas as queries and all chunk embedding_texts
    as the corpus. Measures Recall@1, @3, @5 and MRR@5. Results are
    saved to a CSV by sentence-transformers after each evaluation for
    overfitting analysis.

    Args:
        consultas: Validation consulta dicts (full val split).
        chunks: List of all chunk dicts.

    Returns:
        Configured InformationRetrievalEvaluator.
    """
    corpus = {str(i): chunk["embedding_text"] for i, chunk in enumerate(chunks)}

    chunk_to_idx: dict[str, list[str]] = defaultdict(list)
    for i, chunk in enumerate(chunks):
        chunk_to_idx[chunk["doc_id"]].append(str(i))

    queries = {}
    relevant_docs = {}
    for i, consulta in enumerate(consultas):
        qid = f"q{i}"
        queries[qid] = consulta["query"]
        relevant_docs[qid] = set(chunk_to_idx.get(consulta["doc_id"], []))

    return InformationRetrievalEvaluator(
        queries=queries,
        corpus=corpus,
        relevant_docs=relevant_docs,
        name="val_eval",
        mrr_at_k=[5],
        recall_at_k=[1, 3, 5],
        show_progress_bar=False,
        write_csv=True,
    )


def _run_training_round(
    model: SentenceTransformer,
    train_consultas: list[dict],
    val_consultas: list[dict],
    chunks: list[dict],
    round_num: int,
    epochs: int,
    batch_size: int,
    lr: float,
    device: str,
) -> None:
    """Execute one round of training with chunk re-selection.

    Each round re-embeds all chunks and queries with the current model
    state, selects the best positive (and hard negative) chunk per query,
    then trains for the specified number of epochs.

    Args:
        model: SentenceTransformer being fine-tuned (modified in place).
        train_consultas: Training consulta dicts.
        val_consultas: Validation consulta dicts.
        chunks: All document chunks from chunks.json.
        round_num: Current round number (0-indexed).
        epochs: Number of training epochs for this round.
        batch_size: DataLoader batch size.
        lr: Learning rate.
        device: Torch device string.
    """
    logger.info(f"=== Round {round_num + 1}: re-selecting chunks with current encoder ===")
    examples = build_training_examples(train_consultas, chunks, model)
    has_negatives = sum(1 for e in examples if len(e.texts) == 3)
    logger.info(f"Training examples: {len(examples)} ({has_negatives} with hard negatives)")

    train_dataloader = DataLoader(examples, shuffle=True, batch_size=batch_size)

    logger.info("Loading guide model for GISTEmbedLoss...")
    guide = SentenceTransformer(ENCODER_MODEL, device=device)
    train_loss = losses.GISTEmbedLoss(model, guide)

    evaluator = build_evaluator(val_consultas, chunks)

    logger.info(f"Training round {round_num + 1}: {epochs} epochs, batch_size={batch_size}, lr={lr}")
    model.fit(
        train_objectives=[(train_dataloader, train_loss)],
        evaluator=evaluator,
        epochs=epochs,
        warmup_steps=int(len(train_dataloader) * 0.1),
        evaluation_steps=len(train_dataloader),
        output_path=str(OUTPUT_DIR / "finetuned_encoder"),
        optimizer_params={"lr": lr},
        show_progress_bar=True,
    )


def main() -> None:
    """Fine-tune bge-small-en-v1.5 with iterative chunk re-selection."""
    args = sys.argv[1:]
    device = "cuda"
    warmup_epochs = 5
    final_epochs = 15
    batch_size = 16
    lr = 2e-5

    if "--device" in args:
        device = args[args.index("--device") + 1]
    if "--warmup-epochs" in args:
        warmup_epochs = int(args[args.index("--warmup-epochs") + 1])
    if "--final-epochs" in args:
        final_epochs = int(args[args.index("--final-epochs") + 1])
    if "--batch-size" in args:
        batch_size = int(args[args.index("--batch-size") + 1])

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    logger.info("Loading model...")
    model = SentenceTransformer(ENCODER_MODEL, device=device)

    if not CHUNKS_PATH.exists():
        raise FileNotFoundError(
            f"chunks.json not found at {CHUNKS_PATH}. "
            "Run generate_chunks.py first."
        )
    logger.info(f"Loading chunks from {CHUNKS_PATH}...")
    chunks = json.loads(CHUNKS_PATH.read_text(encoding="utf-8"))
    logger.info(f"Total chunks: {len(chunks)}")

    logger.info("Loading consultas...")
    consultas = json.loads(CONSULTAS_PATH.read_text(encoding="utf-8"))
    logger.info(f"Total consultas: {len(consultas)}")

    train_consultas, val_consultas, test_consultas = split_consultas(consultas)
    logger.info(f"Split — train: {len(train_consultas)}, val: {len(val_consultas)}, test: {len(test_consultas)}")

    split_path = OUTPUT_DIR / "split.json"
    split_path.write_text(
        json.dumps({"train": len(train_consultas), "val": len(val_consultas), "test": len(test_consultas)},
                   indent=2),
        encoding="utf-8",
    )

    _run_training_round(
        model, train_consultas, val_consultas, chunks,
        round_num=0, epochs=warmup_epochs, batch_size=batch_size, lr=lr, device=device,
    )

    logger.info(f"Expanding tokenizer with {len(MASA_TOKENS)} MASA-specific tokens...")
    model.tokenizer.add_tokens(MASA_TOKENS)
    model[0].auto_model.resize_token_embeddings(len(model.tokenizer))
    logger.info(f"Tokenizer vocabulary: {len(model.tokenizer)} tokens")

    _run_training_round(
        model, train_consultas, val_consultas, chunks,
        round_num=1, epochs=final_epochs, batch_size=batch_size, lr=lr, device=device,
    )

    logger.info(f"Fine-tuned encoder saved to {OUTPUT_DIR / 'finetuned_encoder'}")
    logger.info(f"Eval CSV: {OUTPUT_DIR / 'finetuned_encoder' / 'val_eval_results.csv'}")
    logger.info("Review val_eval_results.csv — pick the epoch just before Recall@5 peaks then drops.")


if __name__ == "__main__":
    main()
