from pathlib import Path
from typing import Optional

from loguru import logger

from app.llms.llm import BaseLLM
from app.pipelines.question_pipeline.schemas.rag_seed_schema import RagQuestionSeed
from app.pipelines.question_pipeline.utils.checkpoint_writer import CheckpointWriter
from app.prompts.prompt_loader import prompt_loader


class GeneratedRagQuestion:
    """Container for a generated RAG question before final validation.

    Attributes:
        question_id: Assigned question ID (e.g., Q-00001).
        query: Natural language query generated by LLM.
        tool_call: Canonical tool call from the seed.
        tool_name: Tool name from the seed.
    """

    __slots__ = ("question_id", "query", "tool_call", "tool_name")

    def __init__(self, question_id: str, query: str, tool_call: str, tool_name: str) -> None:
        self.question_id = question_id
        self.query = query
        self.tool_call = tool_call
        self.tool_name = tool_name


class GenerateRagQueriesStep:
    """Step 3-RAG — Generate natural language queries for RAG-dependent seeds.

    Uses the rag_query_generator prompt which embeds sensor readings in queries
    and ensures severity/protocol information is never leaked. Supports
    incremental checkpointing to resume interrupted runs.

    Args:
        llm: LLM provider instance for query generation.
        max_retries: Maximum generation attempts per seed. Default 3.
        checkpoint_path: Optional path for JSONL checkpoint file. When set,
            each generated question is appended immediately and existing
            checkpoint records are loaded to skip already-completed seeds.
    """

    def __init__(
        self,
        llm: BaseLLM,
        max_retries: int = 3,
        checkpoint_path: Optional[Path] = None,
    ) -> None:
        self._llm = llm
        self._max_retries = max_retries
        self._checkpoint = CheckpointWriter(checkpoint_path) if checkpoint_path else None
        self._system_message = prompt_loader.get_system_message_by_type("rag_query_generator")
        self._template = prompt_loader.get_prompt_template_by_type("rag_query_generator")
        self._config = prompt_loader.get_config_by_type("rag_query_generator")

    def execute(
        self,
        seeds: list[RagQuestionSeed],
        id_prefix: str = "Q",
        id_offset: int = 0,
    ) -> tuple[list[GeneratedRagQuestion], list[str]]:
        """Generate one query per RAG seed with incremental checkpointing.

        If a checkpoint file exists, already-completed seeds are loaded and
        skipped. New generations are appended to the checkpoint immediately.

        Args:
            seeds: RAG seeds from the seed generator.
            id_prefix: Prefix for question IDs.
            id_offset: Starting offset for question numbering.

        Returns:
            Tuple of (generated questions, list of failed seed_ids).
        """
        generated: list[GeneratedRagQuestion] = []
        failed: list[str] = []
        total = len(seeds)

        completed_ids: set[str] = set()
        if self._checkpoint:
            existing = self._checkpoint.load_existing()
            for rec in existing:
                completed_ids.add(rec["seed_id"])
                generated.append(GeneratedRagQuestion(
                    question_id=rec["question_id"],
                    query=rec["query"],
                    tool_call=rec["tool_call"],
                    tool_name=rec["tool_name"],
                ))
            if completed_ids:
                logger.info(f"Resumed from checkpoint: {len(completed_ids)} seeds already completed")

        for idx, seed in enumerate(seeds, 1):
            question_id = f"{id_prefix}-{id_offset + idx:05d}"

            if seed.seed_id in completed_ids:
                continue

            if idx % 50 == 0 or idx == 1:
                logger.info(f"[{idx}/{total}] Generating RAG query for {seed.seed_id} ({seed.tool_name}/{seed.metric})")

            query = self._generate_single(seed)
            if not query:
                logger.warning(f"{seed.seed_id}: RAG query generation failed after {self._max_retries} attempts")
                failed.append(seed.seed_id)
                continue

            question = GeneratedRagQuestion(
                question_id=question_id,
                query=query,
                tool_call=seed.tool_call,
                tool_name=seed.tool_name,
            )
            generated.append(question)

            if self._checkpoint:
                self._checkpoint.append({
                    "seed_id": seed.seed_id,
                    "question_id": question_id,
                    "query": query,
                    "tool_call": seed.tool_call,
                    "tool_name": seed.tool_name,
                })

        logger.info(f"RAG query generation complete: {len(generated)} ok, {len(failed)} failed")
        return generated, failed

    def _generate_single(self, seed: RagQuestionSeed) -> str:
        """Generate a query for a single RAG seed with retry logic.

        Args:
            seed: The RAG seed to generate a query for.

        Returns:
            Generated query string, or empty string on failure.
        """
        prompt = self._build_prompt(seed)
        messages = [
            {"role": "system", "content": self._system_message},
            {"role": "user", "content": prompt},
        ]

        for attempt in range(1, self._max_retries + 1):
            try:
                response = self._llm.generate(messages, **self._config)
                query = response.strip().strip('"').strip("'")
                if query and len(query.split()) >= 8:
                    return query
                logger.warning(f"{seed.seed_id}: attempt {attempt} returned short/empty output")
            except Exception as exc:
                logger.warning(f"{seed.seed_id}: attempt {attempt} error — {exc}")

        return ""

    def _build_prompt(self, seed: RagQuestionSeed) -> str:
        """Fill the RAG prompt template with seed data.

        Args:
            seed: RAG seed containing module, metric, reading, etc.

        Returns:
            Formatted prompt string for the LLM.
        """
        return self._template.format(
            tool_name=seed.tool_name,
            module=seed.module,
            metric=seed.metric,
            sensor_reading=seed.sensor_reading,
            incident_description=seed.incident_description,
            rag_requirement=seed.rag_requirement,
            phrasing_index=seed.phrasing_index,
        )
