from enum import Enum
from typing import Optional

from pydantic import BaseModel


class DifficultyLevel(str, Enum):
    """Difficulty tiers for generated questions.

    Attributes:
        easy: Direct query with obvious keyword match to tool and module.
        medium: Indirect query requiring contextual reasoning or multi-hop inference.
        hard: Requires RAG context to determine correct parameters (e.g., severity thresholds).
        trap: Ambiguous query that sounds actionable but correct answer is no_action,
              or query that maps to a different tool than the obvious first guess.
    """

    easy = "easy"
    medium = "medium"
    hard = "hard"
    trap = "trap"


class QuestionSplit(str, Enum):
    """Dataset split assignment for a generated question.

    Attributes:
        train: Included in train_tool_calls.json for student fine-tuning.
        test: Included in test_queries.csv for Kaggle evaluation.
        hidden: Reserved for hidden evaluation run by instructors.
    """

    train = "train"
    test = "test"
    hidden = "hidden"


class QuestionSpec(BaseModel):
    """A fully generated question ready for output.

    Attributes:
        question_id: Unique identifier (e.g., Q-0001).
        query: Natural language operator query generated by LLM.
        tool_call: Canonical tool call string built deterministically from seed.
        tool_name: Name of the correct tool (or 'no_action').
        doc_ids: Document IDs containing facts required to answer this question.
        difficulty: Difficulty tier of the question.
        split: Dataset split assignment (train / test / hidden).
    """

    question_id: str
    query: str
    tool_call: str
    tool_name: str
    doc_ids: list[str]
    difficulty: DifficultyLevel
    split: QuestionSplit


class GenerationBatchResult(BaseModel):
    """Result of a full question generation run.

    Attributes:
        total_generated: Total questions successfully generated.
        total_failed: Questions that failed generation and were skipped.
        distribution: Mapping of tool_name to count of generated questions.
        split_counts: Mapping of split name to count.
        questions: All successfully generated QuestionSpec instances.
    """

    total_generated: int
    total_failed: int
    distribution: dict[str, int]
    split_counts: dict[str, int]
    questions: list[QuestionSpec]
